FROM registry.suse.com/bci/golang:1.22 AS base

# renovate: datasource=github-tags depName=golangci/golangci-lint
ARG GOLANGCI_LINT_VERSION=v1.59.0

RUN zypper -n in bash git-core && \
    zypper clean -a

RUN GOBIN=/usr/local/bin go install github.com/golangci/golangci-lint/cmd/golangci-lint@${GOLANGCI_LINT_VERSION}

WORKDIR /src

FROM base AS ci

COPY . .

RUN mkdir -p bin dist && ./scripts/ci

FROM scratch AS artifacts

COPY --from=ci /src/bin /bin
