// Code generated by MockGen. DO NOT EDIT.
// Source: tests/scarf/interface.go
//
// Generated by this command:
//
//	mockgen -source tests/scarf/interface.go -package scarf -destination tests/scarf/mock.go
//

// Package scarf is a generated GoMock package.
package scarf

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGateway is a mock of Gateway interface.
type MockGateway struct {
	ctrl     *gomock.Controller
	recorder *MockGatewayMockRecorder
	isgomock struct{}
}

// MockGatewayMockRecorder is the mock recorder for MockGateway.
type MockGatewayMockRecorder struct {
	mock *MockGateway
}

// NewMockGateway creates a new mock instance.
func NewMockGateway(ctrl *gomock.Controller) *MockGateway {
	mock := &MockGateway{ctrl: ctrl}
	mock.recorder = &MockGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGateway) EXPECT() *MockGatewayMockRecorder {
	return m.recorder
}

// RecordEvent mocks base method.
func (m *MockGateway) RecordEvent(channel, resolved, latest, clusterID, clientIP string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordEvent", channel, resolved, latest, clusterID, clientIP)
}

// RecordEvent indicates an expected call of RecordEvent.
func (mr *MockGatewayMockRecorder) RecordEvent(channel, resolved, latest, clusterID, clientIP any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordEvent", reflect.TypeOf((*MockGateway)(nil).RecordEvent), channel, resolved, latest, clusterID, clientIP)
}
