name: CI on Push and Pull Request

on:
  pull_request:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: go.mod

      - name: Fix the not-a-git-repository issue
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Go fmt
        run: test -z "$(go fmt ${PACKAGES} | tee /dev/stderr)"

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@55c2c1448f86e01eaae002a5a3a9624417608d84 # v6
        with:
          version: latest

      - name: Build
        run: ./scripts/build

      - name: Test
        run: ./scripts/test
